name: Deploy Frontend to CyberPanel

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18   # safer

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend/

    - name: Build Project
      run: npm run build
      working-directory: ./frontend/

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        local-dir: ./frontend/dist/
        server-dir: /home/resumehub.mhansari.shop/public_html/ 
        dangerous-clean-slate: true